#!/bin/bash
# Run test multiple times
#
if [ $# -ne 3 ]
then
    echo "Usage: omx_sample_multi <processor> <num_processes> <iterations_per_process>"
    exit
fi

for i in `seq 1 $2`
do
echo "Test # " $i
# Uncomment to do in parallel:
#omx_sample $1 $3 &
# or sequential:
omx_sample $1 $3
done
